-- MySQL Script generated by MySQL Workbench
-- Mon Oct 28 14:09:59 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clients` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Types Clients_Id` INT NOT NULL,
  `Garages_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Clients_Types Clients1_idx` (`Types Clients_Id` ASC) VISIBLE,
  INDEX `fk_Clients_Garages1_idx` (`Garages_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Clients_Types Clients1`
    FOREIGN KEY (`Types Clients_Id`)
    REFERENCES `mydb`.`Types Clients` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Clients_Garages1`
    FOREIGN KEY (`Garages_Id`)
    REFERENCES `mydb`.`Garages` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contracts types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contracts types` (
  `ID` INT ZEROFILL NOT NULL,
  `Name` VARCHAR(255) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contracts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contracts` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NULL,
  `Contract TypeID` INT NULL,
  `contracts types_ID` INT ZEROFILL NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_contracts_contracts types_idx` (`contracts types_ID` ASC) VISIBLE,
  CONSTRAINT `fk_contracts_contracts types`
    FOREIGN KEY (`contracts types_ID`)
    REFERENCES `mydb`.`contracts types` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Clients_has_contracts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clients_has_contracts` (
  `Clients_Id` INT NOT NULL,
  `contracts_Id` INT NOT NULL,
  PRIMARY KEY (`Clients_Id`, `contracts_Id`),
  INDEX `fk_Clients_has_contracts_contracts1_idx` (`contracts_Id` ASC) VISIBLE,
  INDEX `fk_Clients_has_contracts_Clients1_idx` (`Clients_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Clients_has_contracts_Clients1`
    FOREIGN KEY (`Clients_Id`)
    REFERENCES `mydb`.`Clients` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Clients_has_contracts_contracts1`
    FOREIGN KEY (`contracts_Id`)
    REFERENCES `mydb`.`contracts` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Types Clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Types Clients` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Type` VARCHAR(255) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Statut Contract`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Statut Contract` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Statut` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Contracts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Contracts` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Statut Contract_id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Contracts_Statut Contract1_idx` (`Statut Contract_id` ASC) VISIBLE,
  CONSTRAINT `fk_Contracts_Statut Contract1`
    FOREIGN KEY (`Statut Contract_id`)
    REFERENCES `mydb`.`Statut Contract` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Clients_has_Contracts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clients_has_Contracts` (
  `Clients_Id` INT NOT NULL,
  `Contracts_Id` INT NOT NULL,
  PRIMARY KEY (`Clients_Id`, `Contracts_Id`),
  INDEX `fk_Clients_has_Contracts_Contracts1_idx` (`Contracts_Id` ASC) VISIBLE,
  INDEX `fk_Clients_has_Contracts_Clients1_idx` (`Clients_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Clients_has_Contracts_Clients1`
    FOREIGN KEY (`Clients_Id`)
    REFERENCES `mydb`.`Clients` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Clients_has_Contracts_Contracts1`
    FOREIGN KEY (`Contracts_Id`)
    REFERENCES `mydb`.`Contracts` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Garages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Garages` (
  `Id` INT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NULL,
  `Echeance de pret` INT NULL,
  `Montant de location` INT NULL,
  `Charges` INT NULL,
  `Clients_has_Contracts_Clients_Id` INT NOT NULL,
  `Clients_has_Contracts_Contracts_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Garages_Clients_has_Contracts1_idx` (`Clients_has_Contracts_Clients_Id` ASC, `Clients_has_Contracts_Contracts_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Garages_Clients_has_Contracts1`
    FOREIGN KEY (`Clients_has_Contracts_Clients_Id` , `Clients_has_Contracts_Contracts_Id`)
    REFERENCES `mydb`.`Clients_has_Contracts` (`Clients_Id` , `Contracts_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clients` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Types Clients_Id` INT NOT NULL,
  `Garages_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Clients_Types Clients1_idx` (`Types Clients_Id` ASC) VISIBLE,
  INDEX `fk_Clients_Garages1_idx` (`Garages_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Clients_Types Clients1`
    FOREIGN KEY (`Types Clients_Id`)
    REFERENCES `mydb`.`Types Clients` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Clients_Garages1`
    FOREIGN KEY (`Garages_Id`)
    REFERENCES `mydb`.`Garages` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Trésorerie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Trésorerie` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Mois et année` VARCHAR(45) NULL,
  `Garages_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Trésorerie_Garages1_idx` (`Garages_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Trésorerie_Garages1`
    FOREIGN KEY (`Garages_Id`)
    REFERENCES `mydb`.`Garages` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Class` (
  `idClass` INT NOT NULL AUTO_INCREMENT,
  `Class Name` VARCHAR(255) NULL,
  PRIMARY KEY (`idClass`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NULL,
  `Prénom` VARCHAR(45) NULL,
  `Rôle` VARCHAR(45) NULL,
  `Adresse mail` VARCHAR(45) NULL,
  `mdp` VARCHAR(45) NULL,
  `Class_idClass` INT NOT NULL,
  PRIMARY KEY (`idUser`, `Class_idClass`),
  INDEX `fk_User_Class1_idx` (`Class_idClass` ASC) VISIBLE,
  CONSTRAINT `fk_User_Class1`
    FOREIGN KEY (`Class_idClass`)
    REFERENCES `mydb`.`Class` (`idClass`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cours`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cours` (
  `Matières` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`Matières`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Emploi du temps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Emploi du temps` (
  `id_edt` INT NOT NULL AUTO_INCREMENT,
  `Cours_Matières` INT NOT NULL,
  `Class_idClass` INT NOT NULL,
  `Horaires` VARCHAR(45) NULL,
  `Emploi du tempscol` VARCHAR(45) NULL,
  PRIMARY KEY (`id_edt`, `Cours_Matières`, `Class_idClass`),
  INDEX `fk_Cours_has_Class_Class1_idx` (`Class_idClass` ASC) VISIBLE,
  INDEX `fk_Cours_has_Class_Cours1_idx` (`Cours_Matières` ASC) VISIBLE,
  CONSTRAINT `fk_Cours_has_Class_Cours1`
    FOREIGN KEY (`Cours_Matières`)
    REFERENCES `mydb`.`Cours` (`Matières`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cours_has_Class_Class1`
    FOREIGN KEY (`Class_idClass`)
    REFERENCES `mydb`.`Class` (`idClass`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '		';


-- -----------------------------------------------------
-- Table `mydb`.`Signature`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Signature` (
  `idSignature` INT NOT NULL AUTO_INCREMENT,
  `User_idUser` INT NOT NULL,
  `Emploi du temps_Cours_Matières` INT NOT NULL,
  `Emploi du temps_Class_idClass` INT NOT NULL,
  PRIMARY KEY (`idSignature`, `User_idUser`, `Emploi du temps_Cours_Matières`, `Emploi du temps_Class_idClass`),
  INDEX `fk_Signature_User1_idx` (`User_idUser` ASC) VISIBLE,
  INDEX `fk_Signature_Emploi du temps1_idx` (`Emploi du temps_Cours_Matières` ASC, `Emploi du temps_Class_idClass` ASC) VISIBLE,
  CONSTRAINT `fk_Signature_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Signature_Emploi du temps1`
    FOREIGN KEY (`Emploi du temps_Cours_Matières` , `Emploi du temps_Class_idClass`)
    REFERENCES `mydb`.`Emploi du temps` (`Cours_Matières` , `Class_idClass`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
